import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { HeadingOne, HeadingTwo } from "./components/Heading";
import { Table, TD, TH, TR } from "@ag-media/react-pdf-table";
import dayjs from "dayjs";

const styles = StyleSheet.create({
  page: {
    padding: '1in',
    width: '6.5in',
    fontSize: 11,
  },
  header: {
    height: '2in',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    border: '1 solid #6b7280',
    marginBottom: 16,
  },
  title: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingBottom: 4,
    marginBottom: 8
  },
  text: {
    marginBottom: 8,
  },
});

export function ConsumableItemReport() {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={{ textAlign: 'center', color: '#6b7280' }}>{"{HEADER PLACEHOLDER}"}</Text>
        </View>
        <View>
          <HeadingOne>Inventory Report</HeadingOne>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Generated By:</Text> NAME</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Position:</Text> POSITION</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Date:</Text> {dayjs().format("MMMM DD, YYYY")}</Text>
        </View>
        <View style={{ marginTop: 16 }}>
          <View style={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between' }}>
            <View style={{ width: '100%' }}>
              <HeadingTwo>[EQUIPMENT ITEM]</HeadingTwo>
              <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Item ID:</Text> 1</Text>
              <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Number of Usage:</Text> 100</Text>
              <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Quantity in Report:</Text> 12000123</Text>
            </View>
            <View style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', width: '100%', border: '1px solid black' }}>
              <Text>Image here</Text>
            </View>
          </View>
        </View>
        <View style={{ marginTop: 16 }}>
          <HeadingOne>Recommendation Report</HeadingOne>
          <Text>Based on the historical and current usage of the [ITEM NAME], it is recommended that the procurement of the item be made from [PREDICTED DATE] with the quantity of [PREDICTED QUANTITY] to ensure uninterrupted use without inventory problems.</Text>
        </View>
      </Page>
      <Page size="LETTER" style={styles.page}>
        <HeadingOne>Summary</HeadingOne>
        <View>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Date Range:</Text> {dayjs().format("MMMM DD, YYYY")}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Entries:</Text> 10</Text>
        </View>

        <View style={{ marginTop: 16 }}>
          <HeadingTwo>Procurement</HeadingTwo>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Amount:</Text> 100</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Entries:</Text> 10</Text>
        </View>

        <View style={{ marginTop: 16 }}>
          <HeadingTwo>Consumption</HeadingTwo>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Amount:</Text> 100</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Entries:</Text> 10</Text>
        </View>
      </Page>

      <Page size="LETTER" style={[styles.page]}>
        <HeadingOne>Usage History of 'ITEM NAME'</HeadingOne>
        <Table tdStyle={{ padding: 2 }} weightings={[0.15, 0.1, 0.2, 0.2, 0.1, 0.25]}>
          <TH>
            <TD>Personnel</TD>
            <TD>Date</TD>
            <TD>Add / Use</TD>
            <TD>Running Total</TD>
            <TD>Task</TD>
            <TD>Task Personnel</TD>
          </TH>
          <TR>
            <TD>Transaction.Creator</TD>
            <TD>Transaction.Created_At</TD>
            <TD>Quantity</TD>
            <TD>Total</TD>
            <TD>Transaction.Task</TD>
            <TD>Transaction.Task.Personnel</TD>
          </TR>
        </Table>
      </Page>
    </Document>
  )
}