import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { HeadingOne, HeadingTwo } from "./components/Heading";
import { Table, TD, TH, TR } from "@ag-media/react-pdf-table";
import dayjs from "dayjs";
import { ConsumableItem, ConsumableTransactionEntry } from "@/types/inventory";
import { Personnel } from "@/types";
import { formatName } from "@/lib/utils";
import Background from './doc-bg.png';

const styles = StyleSheet.create({
  page: {
    padding: '1in',
    width: '6.5in',
    fontSize: 11,
  },
  header: {
    height: '2in',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingBottom: 4,
    marginBottom: 8
  },
  text: {
    marginBottom: 8,
  },
});

interface ReportProps {
  item: ConsumableItem & { entries: (ConsumableTransactionEntry & {  running_total: string })[] };
  creator: Personnel;
  from_date: string;
  to_date: string;
  recommendation: number;
}

export function ConsumableItemReport({ item, creator, from_date, to_date, recommendation }: ReportProps) {
  const procurementEntries = item.entries.filter(entry => entry.quantity >= 0);
  const consumptionEntries = item.entries.filter(entry => entry.quantity < 0);

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Image src={Background} style={{ position: 'absolute', width: '100%', height: '100%', top: 0, left: 0 }} />
        <View style={styles.header} />
        <View>
          <HeadingOne>Inventory Report</HeadingOne>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Generated By:</Text> {formatName(creator)}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Position:</Text> {creator.position ?? 'CDRRMO Personnel'}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Date:</Text> {dayjs().format("MMMM DD, YYYY")}</Text>
        </View>
        <View style={{ marginTop: 16 }}>
          <View style={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between' }}>
            <View style={{ width: '100%' }}>
              <HeadingTwo>{item.name}</HeadingTwo>
              <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Item ID:</Text> {item.id}</Text>
              <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Description:</Text> {item.description}</Text>
            </View>
          </View>
        </View>

        {item.model_identifier && (
          <View style={{ marginTop: 16 }}>
            <HeadingOne>Recommendation Report</HeadingOne>
            <Text>Based on the historical and current usage of the <Text style={{ fontWeight: 'bold' }}>{item.name}</Text>, it is recommended that the procurement of the item be made for {dayjs().format("MMMM YYYY")} with the quantity of <Text style={{fontWeight: 'bold'}}>{recommendation}</Text> to ensure uninterrupted use without inventory problems.</Text>
          </View>
        )}
      </Page>
      <Page size="LETTER" style={styles.page}>
        <HeadingOne>Summary</HeadingOne>
        <View>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Date Range:</Text> {dayjs(from_date, "YYYY-MM").format("MMMM YYYY")} to {dayjs(to_date, "YYYY-MM").format("MMMM YYYY")}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Entries:</Text> {item.entries.length}</Text>
        </View>
        
        <View style={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between' }}>
          <View style={{ marginTop: 16, width: '100%' }}>
            <HeadingTwo>Procurement</HeadingTwo>
            <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Quantity:</Text> {procurementEntries.reduce((sum, entry) => sum + entry.quantity, 0)}</Text>
            <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Entries:</Text> {procurementEntries.length}</Text>
          </View>
          <View style={{ marginTop: 16, width: '100%' }}>
            <HeadingTwo>Consumption</HeadingTwo>
            <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Quantity:</Text> {Math.abs(consumptionEntries.reduce((sum, entry) => sum + entry.quantity, 0))}</Text>
            <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Entries:</Text> {consumptionEntries.length}</Text>
          </View>
        </View>
      </Page>

      <Page size="LETTER" style={[styles.page]}>
        <HeadingOne>Usage History of '{item.name}'</HeadingOne>
        <Table tdStyle={{ padding: 2 }} weightings={[0.25, 0.15, 0.15, 0.1, 0.1, 0.25]}>
          <TH>
            <TD>Personnel</TD>
            <TD>Date</TD>
            <TD>Add / Use</TD>
            <TD>Total</TD>
            <TD>Task</TD>
            <TD>Task Personnel</TD>
          </TH>
          {item.entries.map(entry => (
            <TR
              key={entry.id}
            >
              <TD>{formatName(entry.transaction.personnel)}</TD>
              <TD>{dayjs(entry.transaction.created_at).format("MM/DD/YYYY")}</TD>
              <TD>{entry.quantity}</TD>
              <TD>{entry.running_total}</TD>
              <TD>{entry.transaction.task?.title}</TD>
              <TD style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>{entry.transaction.task ? entry.transaction.task.personnel.map(person => (
                <Text>{formatName(person)}</Text>
              )) : ''}</TD>
            </TR>
          ))}
        </Table>
      </Page>
    </Document>
  )
}