import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { HeadingOne } from "./components/Heading";
import { Table, TD, TH, TR } from "@ag-media/react-pdf-table";
import { PersonnelWithLocationHistory } from "@/Pages/Mapping/Partials/GenerateLocationHistoryReportDialog";
import dayjs from "dayjs";
import { formatName } from "@/lib/utils";

const styles = StyleSheet.create({
  page: {
    padding: '1in',
    width: '6.5in',
    fontSize: 11,
  },
  header: {
    height: '2in',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    border: '1 solid #6b7280',
    marginBottom: 16,
  },
  title: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingBottom: 4,
    marginBottom: 8
  },
  text: {
    marginBottom: 8,
  },
});

export function EquipmentItemReport() {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={{ textAlign: 'center', color: '#6b7280' }}>{"{HEADER PLACEHOLDER}"}</Text>
        </View>
        <View>
          <HeadingOne>Inventory Report</HeadingOne>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Generated By:</Text> NAME</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Position:</Text> POSITION</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Generated By:</Text> {dayjs().format("MMMM DD, YYYY")}</Text>
        </View>
      </Page>
    </Document>
  )
}