import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { HeadingOne, HeadingTwo } from "./components/Heading";
import { Table, TD, TH, TR } from "@ag-media/react-pdf-table";
import dayjs from "dayjs";
import { EquipmentGroup, EquipmentItem, EquipmentTransactionEntry } from "@/types/inventory";
import { Personnel } from "@/types";
import { formatName } from "@/lib/utils";

const styles = StyleSheet.create({
  page: {
    padding: '1in',
    width: '6.5in',
    fontSize: 11,
  },
  header: {
    height: '2in',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    border: '1 solid #6b7280',
    marginBottom: 16,
  },
  title: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingBottom: 4,
    marginBottom: 8
  },
  text: {
    marginBottom: 8,
  },
});

interface ReportProps {
  group: EquipmentGroup & {
    items: (EquipmentItem & { entries: EquipmentTransactionEntry[] })[];
  };
  selectedItems: string[];
  creator: Personnel;
}

export function EquipmentItemReport({ group, selectedItems, creator }: ReportProps) {
  const items = group.items.filter(item => selectedItems.includes(String(item.id)))
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={{ textAlign: 'center', color: '#6b7280' }}>{"{HEADER PLACEHOLDER}"}</Text>
        </View>
        <View>
          <HeadingOne>Inventory Report</HeadingOne>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Generated By:</Text> {formatName(creator)}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Position:</Text> {creator.position ?? 'CDRRMO Personnel'}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Date:</Text> {dayjs().format("MMMM DD, YYYY")}</Text>
        </View>
        <View style={{ marginTop: 16 }}>
          <HeadingTwo>Equipment Group: {group.name}</HeadingTwo>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Group ID:</Text> {group.id}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Type:</Text> {group.type.name}</Text>
        </View>
      </Page>
      <Page size="LETTER" style={styles.page}>
        <HeadingOne>Summary</HeadingOne>
        <View>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Date Range:</Text> {dayjs().format("MMMM DD, YYYY")}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Entries:</Text> 10</Text>
        </View>
        {items.map(item => (
          <View key={item.id} style={{ marginTop: 8, borderBottom: 1, borderBottomColor: 'black', paddingBottom: 8 }}>
            <View style={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between' }}>
              <View style={{ width: '100%' }}>
                <HeadingTwo>{item.name}</HeadingTwo>
                <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Item ID:</Text> {item.id}</Text>
                <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Number of Usage:</Text> {item.entries.length}</Text>
              </View>
              <View style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', width: '100%', border: '1px solid black' }}>
                <Text>Image here</Text>
              </View>
            </View>
          </View>
        ))}
      </Page>

      {items.map(item => (
        <Page size="LETTER" style={styles.page}>
          <HeadingOne>Usage History of '{item.name}'</HeadingOne>
          <Table tdStyle={{ padding: 2 }}>
            <TH>
              <TD>Personnel</TD>
              <TD>Date</TD>
              <TD>Details</TD>
              <TD>Task</TD>
              <TD>Task Personnel</TD>
            </TH>
            {item.entries.map(entry => (
              <TR key={entry.id}>
                <TD>{formatName(entry.transaction.personnel)}</TD>
                <TD>{dayjs(entry.transaction.created_at).format("MM/DD/YYYY")}</TD>
                <TD>{entry.transaction.title}</TD>
                <TD>{entry.transaction.task?.title}</TD>
                <TD style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>{entry.transaction.task ? entry.transaction.task.personnel.map(person => (
                <Text>{formatName(person)}</Text>
              )) : ''}</TD>
              </TR>
            ))}
          </Table>
        </Page>
      ))}
    </Document>
  )
}