import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { HeadingOne, HeadingTwo } from "./components/Heading";
import { Table, TD, TH, TR } from "@ag-media/react-pdf-table";
import dayjs from "dayjs";
import { Personnel } from "@/types";
import { ActivityDetail, ActivityType } from "@/types/activities";
import { formatName } from "@/lib/utils";
import Background from './doc-bg.png';

const styles = StyleSheet.create({
  page: {
    padding: '1in',
    width: '6.5in',
    fontSize: 11,
  },
  header: {
    height: '2in',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  text: {
    marginBottom: 8,
  },
  activityItem: {
    marginBottom: 12,
    padding: 8,
    backgroundColor: '#f9fafb',
    borderRadius: 4,
  },
  activityTime: {
    fontSize: 10,
    color: '#6b7280',
    marginBottom: 4,
  },
  activityDescription: {
    fontSize: 11,
    color: '#111827',
  },
});

interface ReportProps {
  personnel: Personnel & {
    activities: ActivityDetail[],
  };
  creator: Personnel;
  date: string; // format: YYYY-MM-DD
}

export function PersonnelActivityReport({ personnel, creator, date }: ReportProps) {
  const activitiesForDate = personnel.activities.filter(
    activity => dayjs(activity.created_at).format("YYYY-MM-DD") === date
  );

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Image src={Background} style={{ position: 'absolute', width: '100%', height: '100%', top: 0, left: 0 }} />
        <View style={styles.header} />
        <View>
          <HeadingOne>Personnel Activity Report</HeadingOne>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Generated By:</Text> {formatName(creator)}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Position:</Text> {creator.position ?? 'CDRRMO Personnel'}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Date:</Text> {dayjs().format("MMMM DD, YYYY")}</Text>
        </View>
        
        <View style={{ marginTop: 16 }}>
          <View style={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between' }}>
            <View style={{ width: '100%' }}>
              <HeadingTwo>Personnel Information</HeadingTwo>
              <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Name:</Text> {formatName(personnel)}</Text>
              <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Personnel ID:</Text> {personnel.id}</Text>
              <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Position:</Text> {personnel.position ?? 'CDRRMO Personnel'}</Text>
            </View>
          </View>
        </View>

        <View style={{ marginTop: 16 }}>
          <HeadingTwo>Activity Summary</HeadingTwo>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Date:</Text> {dayjs(date, "YYYY-MM-DD").format("MMMM DD, YYYY")}</Text>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Total Activities:</Text> {activitiesForDate.length}</Text>
        </View>
      </Page>

      <Page size="LETTER" style={styles.page}>
        <HeadingOne>Activity Details for {dayjs(date, "YYYY-MM-DD").format("MMMM DD, YYYY")}</HeadingOne>
        
        <Table tdStyle={{ padding: 4 }} weightings={[0.2, 0.3, 0.5]}>
          <TH>
            <TD>Time</TD>
            <TD>Activity Type</TD>
            <TD>Description</TD>
          </TH>
          {activitiesForDate.map((activity, index) => (
            <TR key={index}>
              <TD>{dayjs(activity.created_at).format("hh:mm A")}</TD>
              <TD>{formatActivityType(activity.activity_type)}</TD>
              <TD>{getActivityDescription(activity)}</TD>
            </TR>
          ))}
        </Table>

        {activitiesForDate.length === 0 && (
          <View style={{ marginTop: 16, textAlign: 'center' }}>
            <Text style={{ color: '#6b7280' }}>No activities recorded for this date.</Text>
          </View>
        )}
      </Page>
    </Document>
  );
}

// Helper function to format activity type
function formatActivityType(type: ActivityType): string {
  const typeMap: Record<ActivityType, string> = {
    'login_activity': 'Login',
    'logout_activity': 'Logout',
    'start_task_activity': 'Task Start',
    'finish_task_activity': 'Task Finish',
    'change_status_activity': 'Status Change',
    'cancel_task_activity': 'Task Cancel',
  };
  return typeMap[type] || type;
}

// Helper function to generate activity description
function getActivityDescription(activity: ActivityDetail): string {
  const { activity_type, activity: activityData } = activity;

  switch (activity_type) {
    case 'login_activity':
      return `Logged in from ${activityData.device_name || 'Unknown Device'}`;
    
    case 'logout_activity':
      return `Logged out from ${activityData.device_name || 'Unknown Device'}`;
    
    case 'start_task_activity':
      return `Started task: ${activityData.task?.title || 'Unknown Task'}`;
    
    case 'finish_task_activity':
      return `Finished task: ${activityData.task?.title || 'Unknown Task'}`;
    
    case 'cancel_task_activity':
      return `Cancelled task: ${activityData.task?.title || 'Unknown Task'}`;
    
    case 'change_status_activity':
      return `Changed status from ${activityData.old_status || 'Unknown'} to ${activityData.new_status || 'Unknown'}`;
    
    default:
      return 'Activity recorded';
  }
}